/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontPage;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ABHINAV ANAND
 */
public class BookingDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form BookingDetails
     */
    String uname;
    public BookingDetails(String uname) {
        this.uname = uname;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        details = new javax.swing.JTable();
        show = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Booking Details");

        details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(details);

        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(show)
                .addGap(259, 259, 259))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(show)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        
        try{
            Connection con = null;
            Class.forName("com.mysql.jdbc.Driver");

            String databaseUrl = "jdbc:mysql://localhost:3307/daretotravel";
            try {
            con = (Connection) DriverManager.getConnection(databaseUrl, "root","anand1234");
            } catch (SQLException ex) {
                Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
            }

            
            Statement stat = (Statement) con.createStatement();
            String selectQuery = "SELECT * FROM `booking_details` WHERE `user_booked` ='"+uname+"'";
            ResultSet rs = stat.executeQuery(selectQuery);
            
            details.setModel(DbUtils.resultSetToTableModel(rs));
            details.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            
            
            
            

        }
        catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_showActionPerformed

    private void detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailsMouseClicked
        // TODO add your handling code here:

        int index = details.getSelectedRow();
        TableModel model = details.getModel();

        int sno = Integer.parseInt(model.getValueAt(index, 0).toString());
        int id = Integer.parseInt(model.getValueAt(index, 1).toString());
        String train_name = (String) model.getValueAt(index, 3);
        int train_no = Integer.parseInt(model.getValueAt(index, 2).toString());
        String train_source = (String) model.getValueAt(index, 4);
        String train_dest = (String) model.getValueAt(index, 5);
        String train_route = (String) model.getValueAt(index, 6);
        String coach = (String) model.getValueAt(index, 7);
        //        int ac_II_S = Integer.parseInt(model.getValueAt(index, 8).toString());
        //        int ac_II_P = Integer.parseInt(model.getValueAt(index, 9).toString());
        int amtp = Integer.parseInt(model.getValueAt(index, 15).toString());
        //        int sleeper_P = Integer.parseInt(model.getValueAt(index, 11).toString());

        String departTime = (String) model.getValueAt(index, 8);
        String status = (String) model.getValueAt(index, 9);
        String fname = (String) model.getValueAt(index, 10);
        String lname = (String) model.getValueAt(index, 11);
        int nseats = Integer.parseInt(model.getValueAt(index, 12).toString());
        Date train_date = (Date) model.getValueAt(index, 13);
        String ubooked = (String) model.getValueAt(index, 14);

        //        int avl_ac_II_S = Integer.parseInt(model.getValueAt(index, 13).toString());
        //        int avl_sleeper_S = Integer.parseInt(model.getValueAt(index, 14).toString());
        String tstatus = (String) model.getValueAt(index, 16);
        String meals = (String) model.getValueAt(index, 17);
        int wstatus = Integer.parseInt(model.getValueAt(index, 18).toString());

        BookmelsORcancelTickets boft = new BookmelsORcancelTickets(sno, id, train_no, train_name, train_source, train_dest, train_route, coach, departTime, status, fname, lname, train_date, uname, nseats, amtp, tstatus, meals, wstatus);
        boft.setVisible(true);
        boft.pack();
        //        bof.

        //         JOptionPane.showMessageDialog(null, "Clicked", "Clicked!", HEIGHT);

    }//GEN-LAST:event_detailsMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
       
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();

        int sno = Integer.parseInt(model.getValueAt(index, 0).toString());
        int id = Integer.parseInt(model.getValueAt(index, 1).toString());
        String train_name = (String) model.getValueAt(index, 3);
        int train_no = Integer.parseInt(model.getValueAt(index, 2).toString());
        String train_source = (String) model.getValueAt(index, 4);
        String train_dest = (String) model.getValueAt(index, 5);
        String train_route = (String) model.getValueAt(index, 6);
        String coach = (String) model.getValueAt(index, 7);
        //        int ac_II_S = Integer.parseInt(model.getValueAt(index, 8).toString());
        //        int ac_II_P = Integer.parseInt(model.getValueAt(index, 9).toString());
        int amtp = Integer.parseInt(model.getValueAt(index, 15).toString());
        //        int sleeper_P = Integer.parseInt(model.getValueAt(index, 11).toString());

        String departTime = (String) model.getValueAt(index, 8);
        String status = (String) model.getValueAt(index, 9);
        String fname = (String) model.getValueAt(index, 10);
        String lname = (String) model.getValueAt(index, 11);
        int nseats = Integer.parseInt(model.getValueAt(index, 12).toString());
        Date train_date = (Date) model.getValueAt(index, 13);
        String ubooked = (String) model.getValueAt(index, 14);

        //        int avl_ac_II_S = Integer.parseInt(model.getValueAt(index, 13).toString());
        //        int avl_sleeper_S = Integer.parseInt(model.getValueAt(index, 14).toString());
        String tstatus = (String) model.getValueAt(index, 16);
        String meals = (String) model.getValueAt(index, 17);
        int wstatus = Integer.parseInt(model.getValueAt(index, 18).toString());

        BookmelsORcancelTickets bofq = new BookmelsORcancelTickets(sno, id, train_no, train_name, train_source, train_dest, train_route, coach, departTime, status, fname, lname, train_date, ubooked, nseats, amtp, tstatus, meals,wstatus);
        bofq.setVisible(true);
        bofq.pack();
        //        bof.

        //         JOptionPane.showMessageDialog(null, "Clicked", "Clicked!", HEIGHT);

    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable details;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton show;
    // End of variables declaration//GEN-END:variables
}
