/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontPage;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ABHINAV ANAND
 */
public class EditTrainsInfo extends javax.swing.JFrame {

    /**
     * Creates new form EditTrainsInfo
     */
    public EditTrainsInfo() {
        initComponents();
    }

    int id, train_no, ac_II_S, ac_II_P, sleeper_S, sleeper_P, avl_ac_II_S, avl_sleeper_S;
    String train_name, source, dest, route, time, status, uname;
    Date date;
    public EditTrainsInfo(int id, int train_no, String train_name, String source, String dest, String route, int ac_II_S, int ac_II_P, int sleeper_S, int sleeper_P, String time, String status, Date date, String uname, int avl_ac_II_S, int avl_sleeper_S){
        initComponents();
        this.id = id;
        this.train_no = train_no;
        this.train_name = train_name;
        this.source = source;
        this.dest = dest;
        this.route = route;
        this.ac_II_S = ac_II_S;
        this.ac_II_P = ac_II_P;
        this.sleeper_S = sleeper_S;
        this.sleeper_P = sleeper_P;
//        this.coach = coach;
        this.time = time;
        this.status = status;
        this.date = date;
        this.uname = uname;
        this.avl_ac_II_S = avl_ac_II_S;
        this.avl_sleeper_S = avl_sleeper_S;
        
        jLabel4.setText(String.valueOf(id));
        jLabel8.setText(String.valueOf(train_no));
        jLabel6.setText(train_name);
        jLabel10.setText(source);
        jLabel12.setText(dest);
        jLabel14.setText(String.valueOf(ac_II_S));
        jLabel16.setText(String.valueOf(sleeper_S));
        jLabel18.setText(String.valueOf(ac_II_P));
        jLabel20.setText(String.valueOf(sleeper_P));
        jLabel31.setText(route);
//        jLabel19.setText(time);
//        jLabel20.setText(status);
//        jLabel24.setText(String.valueOf(date));
        jLabel22.setText(String.valueOf(avl_ac_II_S));
        jLabel24.setText(String.valueOf(avl_sleeper_S));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Trains Info");

        jLabel1.setText("EDIT TRAINS");

        jLabel2.setText("train_status");

        jLabel3.setText("id");

        jLabel5.setText("train_name");

        jLabel13.setText("AC II Seats");

        jLabel17.setText("AC II Price");

        jLabel18.setText("jLabel18");

        jLabel14.setText("jLabel14");

        jLabel6.setText("jLabel6");

        jLabel4.setText("jLabel4");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Running", "Cancelled", " " }));

        jLabel7.setText("train_no");

        jLabel9.setText("train_source");

        jLabel11.setText("train_dest");

        jLabel15.setText("Sleeper Seats");

        jLabel19.setText("Sleeper Price");

        jLabel20.setText("jLabel20");

        jLabel16.setText("jLabel16");

        jLabel12.setText("jLabel12");

        jLabel10.setText("jLabel10");

        jLabel8.setText("jLabel8");

        jLabel21.setText("Avl AC  II Seats");

        jLabel22.setText("jLabel22");

        jLabel23.setText("Avl Sleeper Seats");

        jLabel24.setText("jLabel24");

        jLabel25.setText("train_route");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hogwarts", "Hogsmeed", "Paris", "London", "DiagonAlly", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel26.setText("add AC II Seats");

        jLabel27.setText("add Sleeper Seats ");

        jLabel28.setText("new AC II Price");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel29.setText("new Sleeper Price");

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel30.setText("current_route");

        jLabel31.setText("jLabel31");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel30))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel29))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel26))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel23))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel21))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel28)))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jButton1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel26)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel27)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel25)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String ntstatus = (String) jComboBox1.getSelectedItem();
        String ntroute = (String) jComboBox2.getSelectedItem();
        String ac_2_s = jTextField1.getText();
        String sl_s = jTextField2.getText();
        String ac_2_p = jTextField3.getText();
        String sl_p = jTextField4.getText();
        
        String ticket_s = "";
        int w_s = 0;
        String meal_s = "";
        String meal_d = "";
        
        if(ntstatus.equals("Cancelled")){
            try {
                Connection con = null;
                Class.forName("com.mysql.jdbc.Driver");

                String databaseUrl = "jdbc:mysql://localhost:3307/daretotravel";
                try {
                    con = (Connection) DriverManager.getConnection(databaseUrl, "root", "anand1234");
                } catch (SQLException ex) {
                    Logger.getLogger(NewUser1.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                String insertQuery = "UPDATE `train_details` SET `train_status` = '" + ntstatus + "' WHERE `train_no` = '" + train_no + "' AND `id` = '"+ id +"'";

                ticket_s = "Invalid";
                w_s = 0;
                meal_s = "Invalid";
                meal_d = "Invalid";
                
                String insertQuery2 = "UPDATE `booking_details` SET `train_status` = '" + ntstatus + "', `ticket_status` = '"+ticket_s+"', `meals_status` = '"+meal_s+"', `meal_dest` = '"+meal_d+"', `waiting_status` = '"+w_s+"' WHERE `train_no` = '" + train_no + "' AND `id` = '"+ id +"'";
                
                Statement stat = (Statement) con.createStatement();
                Statement stat2 = (Statement) con.createStatement();

                int x = stat.executeUpdate(insertQuery);
                int y = stat2.executeUpdate(insertQuery2);
                System.out.print(x);
                System.out.println(y);

                if (x == 1 && y == 1) {
                    NewUser1.infoMessage("Train Cancelled Successfully!", "Alert");
                }

            } catch (ClassNotFoundException | SQLException e) {
                System.out.println(e);
            }
        
        }
        else{
            
            try {
                Connection con = null;
                Class.forName("com.mysql.jdbc.Driver");

                String databaseUrl = "jdbc:mysql://localhost:3307/daretotravel";
                try {
                    con = (Connection) DriverManager.getConnection(databaseUrl, "root", "anand1234");
                } catch (SQLException ex) {
                    Logger.getLogger(NewUser1.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                String insertQuery = "UPDATE `train_details` SET `train_status` = '" + ntstatus + "', `train_route` = '"+ntroute+"', `ACII_Seats` = `ACII_Seats`+'"+ac_2_s+"', `ACII_Price` = '"+ac_2_p+"', `Sleeper_Seats` = `Sleeper_Seats`+'"+sl_s+"', `Sleeper_Price` = '"+sl_p+"', `avl_acII_seats` = `avl_acII_seats`+'"+ac_2_s+"',`avl_sleeper_seats` = `avl_sleeper_seats`+'"+sl_s+"'  WHERE `train_no` = '" + train_no + "' AND `id` = '"+ id +"'";

                Statement stat = (Statement) con.createStatement();
                int x = stat.executeUpdate(insertQuery);
                int a=0,z=0;
                String sql2 = "SELECT * FROM `booking_details` WHERE `id` = '"+id+"' ";
                PreparedStatement st2 = (PreparedStatement) con.prepareStatement(sql2);
//                st2.setInt(2, id);
                ResultSet rs2 = st2.executeQuery();
                while(rs2.next()) {
                    String wait_status = rs2.getString(19);
//                    String nseats = rs2.getString(13);
                    String tstatus = rs2.getString(17);
                    String coach = rs2.getString(8);
//                    String sno = rs2.getString(1);
                    String meal_dest = rs2.getString(19);
                    if(meal_dest.equals(route)){
                        meal_dest = ntroute;
                    }
                    String bookedroute = rs2.getString(7);
                    bookedroute = ntroute;
//                    nseats = Integer.parseInt(nseats);
                    int wstat = Integer.parseInt(wait_status);
//                    System.out.println("wstat "+wstat);
                    String snum = rs2.getString(1);
                    
                    if(tstatus.equals("confirmed")){
                        String insertQuery4 = "UPDATE `booking_details` SET `train_route` = '"+bookedroute+"', `meal_dest` = '"+meal_dest+"' WHERE `train_no` = '" + train_no + "' AND `id` = '"+ id +"' AND `train_coach` = '"+coach+"' AND `sno` = '"+snum+"'";
                
                        Statement stat4 = (Statement) con.createStatement();
                        a = stat4.executeUpdate(insertQuery4);
                    }
                    
                    
                    else if(tstatus.equals("waiting")){
                        if(coach.toLowerCase().contains("ac")){
                            wstat = Integer.parseInt(ac_2_s) + wstat;
                        }
                        else{
                            wstat = Integer.parseInt(sl_s) + wstat;
                        }
                        if(wstat >= 0){
                            tstatus = "confirmed";
                            
                            wstat = 0;
                            String insertQuery4 = "UPDATE `booking_details` SET `ticket_status` = '"+tstatus+"',`train_route` = '"+bookedroute+"', `meal_dest` = '"+meal_dest+"', `waiting_status` = '"+wstat+"' WHERE `train_no` = '" + train_no + "' AND `id` = '"+ id +"' AND `train_coach` = '"+coach+"' AND `sno` = '"+snum+"'";
                
                        Statement stat4 = (Statement) con.createStatement();
                        a = stat4.executeUpdate(insertQuery4);
                        }
                        else{
                            String insertQuery4 = "UPDATE `booking_details` SET `ticket_status` = '"+tstatus+"',`train_route` = '"+bookedroute+"', `meal_dest` = '"+meal_dest+"', `waiting_status` = '"+wstat+"' WHERE `train_no` = '" + train_no + "' AND `id` = '"+ id +"' AND `train_coach` = '"+coach+"' AND `sno` = '"+snum+"'";
                
                        Statement stat4 = (Statement) con.createStatement();
                        a = stat4.executeUpdate(insertQuery4);
                        }
                    }
                if(x==1){
                    NewUser1.infoMessage(" x Cancelled Successfully!", "Alert");
                    
                }
                
                if(a==1){
                    NewUser1.infoMessage(" z Cancelled Successfully!", "Alert");
                    
                }
                    
                }

            } catch (ClassNotFoundException | SQLException e) {
                System.out.println(e);
            }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTrainsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTrainsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTrainsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTrainsInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTrainsInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
